# Generated by Django 4.2.5 on 2023-09-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='nationality',
            new_name='citizenship',
        ),
    ]
