# Generated by Django 4.2.5 on 2023-10-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_nationality_document_citizenship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='orders.order'),
        ),
    ]
